### ISSUE TITLE
Cannot rise a pull request!

### ISSUE THREAD

**Issue by sanjaypradeep** [pylenin/Python30#2]
Here's the error info, 

remote: Permission to pylenin/Python30.git denied to sanjaypradeep.
fatal: unable to access 'https://github.com/pylenin/Python30.git/': The requested URL returned error: 403

**Comment by sanjaypradeep** [comment]
I've raised a PR, after forking your repo. But without forking, is there a possibility?

**Comment by pylenin** [comment]
Not sure if that is the right way. The reason you got a **permission denied** error because, in order for you to create a PR, you have to be given access rights. I am not sure how many students are following this course. So practically it is not possible for me to provide access to everyone. So the ideal way is to fork it. Sorry about that.
